export type EmotionCategory = 'basic' | 'positive' | 'negative' | 'social';

export type TransitionType =
  | 'ACUTE'   // 単一事象トリガーによる急性遷移
  | 'APPR'    // 再評価・認知シフトによる遷移
  | 'INTENS'  // 同一状態の強度増大
  | 'CHRONIC' // 慢性化・状態の固着
  | 'RESOLV'  // 解消・消退
  | 'BLEND';  // 二感情の混合

export interface AppraisalProfile {
  nov: number;   // 新奇性・不確実性 -2(既知) ～ 2(未知)
  pleas: number; // 快・不快 -2(不快) ～ 2(快)
  goal: number;  // 目標整合性 -2(阻害) ～ 2(促進)
  cope: number;  // 対処可能性 -2(無力) ～ 2(十分)
  norm: number;  // 規範整合性 -2(逸脱) ～ 2(適合)
}

export interface TemporalProfile {
  onset: number;   // 発現までの秒数
  peak: number;    // ピークまでの分数
  decay: number;   // 半減期（分）
  persist: number; // 持続時間（時間）
}

export interface RegulationProfile {
  adaptive: string[];        // 適応的な調整方略
  reappraisal: string[];     // 再評価の方向性
  contraindicated: string[]; // 逆効果な方略
}

export interface EmotionTransition {
  to: string;
  label: string;
  type: TransitionType;
}

export interface Emotion {
  id: string;
  name: string;
  nameEn: string;
  category: EmotionCategory;
  coreTheme: string;
  triggers: string[];
  process: string[];
  bodyReactions: string[];
  function: string;
  transitions: EmotionTransition[];
  valence: number;    // -2 to 2
  arousal: number;    // -2 to 2
  dominance: number;  // -2(無力) ～ 2(支配) PAD第3軸
  appraisal: AppraisalProfile;
  temporal: TemporalProfile;
  regulation: RegulationProfile;
  references: string[];
}

export const emotions: Emotion[] = [
  // ── 基本感情 ──────────────────────────────────────────────────
  {
    id: 'joy',
    name: '喜び',
    nameEn: 'Joy / Happiness',
    category: 'basic',
    coreTheme: '目標の達成・肯定的な予測誤差',
    triggers: [
      '目標の達成（合格通知、プロジェクト完遂）',
      '予想を上回る肯定的出来事',
      '親密な他者との再会',
      '美的経験（音楽、自然、芸術）',
      '身体的快（おいしい食事、温浴）',
    ],
    process: [
      '肯定的な認知的評価',
      '腹側被蓋野からドーパミン放出（報酬予測誤差）',
      '副交感神経が優位になりつつ軽い興奮状態',
      'デュシェンヌ型の真の笑い（大頬骨筋＋眼輪筋）',
      '行動傾向：接近・共有・繰り返し',
    ],
    bodyReactions: [
      '口角の挙上と目尻のしわ（デュシェンヌ・スマイル）',
      '心拍のやや上昇、呼吸が深く軽い',
      '筋肉の弛緩、胸の温かみ',
      '神経伝達物質：ドーパミン、内因性オピオイド、オキシトシン',
    ],
    function: '報酬経路の強化を通じて適応行動を学習させる。思考と行動のレパートリーを拡張し（broaden-and-build）、長期的な心理・社会・身体資源を形成する。',
    transitions: [
      { to: 'pride', label: '自己帰属', type: 'APPR' },
      { to: 'gratitude', label: '他者への帰属', type: 'APPR' },
      { to: 'flow', label: '活動没入', type: 'INTENS' },
      { to: 'contentment', label: '強度の減衰', type: 'RESOLV' },
      { to: 'anxiety', label: '次への不安', type: 'APPR' },
    ],
    valence: 2, arousal: 1, dominance: 1,
    appraisal: { nov: 1, pleas: 2, goal: 2, cope: 2, norm: 1 },
    temporal: { onset: 2, peak: 5, decay: 60, persist: 4 },
    regulation: {
      adaptive: ['感謝の表現', '喜びの共有', '味わい（savoring）'],
      reappraisal: ['偶然の幸運への気づき', '人とのつながりの価値の認識'],
      contraindicated: ['他者との比較による格下げ', '喜びの感情抑圧'],
    },
    references: ['Fredrickson (2001)', 'Kringelbach & Berridge (2009)'],
  },
  {
    id: 'sadness',
    name: '悲しみ',
    nameEn: 'Sadness',
    category: 'basic',
    coreTheme: '価値あるものの喪失',
    triggers: [
      '近親者・ペットの死',
      '恋人との別離',
      '夢の挫折、信頼の裏切り',
      '思い出深い場所・物の喪失',
      '他者の悲しみへの共感',
    ],
    process: [
      '「変えられない喪失」という認知の定着',
      '「対処不可能だ」という二次評価',
      '副交感神経優位、活動性の低下',
      '眼窩前頭皮質・前帯状皮質・島皮質の活性化',
      '涙、口角の下降、姿勢の崩れ',
    ],
    bodyReactions: [
      '眉の内側挙上（悲しみの三角）、口角下降',
      '心拍低下、呼吸が浅く長い',
      '胸の重さ・締めつけ感、喉の締まり',
      '神経伝達物質：セロトニン低下、コルチゾール上昇',
    ],
    function: '①援助呼びかけの社会的シグナル ②活動停止と内省による目標の再調整 ③取り戻せない損失へのエネルギー投資を止める。',
    transitions: [
      { to: 'grief', label: '長期化・深化', type: 'CHRONIC' },
      { to: 'anger', label: '不当性の認知', type: 'APPR' },
      { to: 'nostalgia', label: '温かい記憶の混入', type: 'BLEND' },
      { to: 'anxiety', label: '将来への不安を伴う', type: 'BLEND' },
      { to: 'contentment', label: '受容・統合', type: 'RESOLV' },
    ],
    valence: -2, arousal: -1, dominance: -1,
    appraisal: { nov: 0, pleas: -2, goal: -2, cope: -1, norm: 1 },
    temporal: { onset: 30, peak: 10, decay: 90, persist: 24 },
    regulation: {
      adaptive: ['表現・言語化', 'セルフ・コンパッション', '意味の探索'],
      reappraisal: ['喪失を成長の契機として再評価', '残っているものへの注意の転換'],
      contraindicated: ['反芻', '感情の抑圧', '孤立'],
    },
    references: ['Bonanno (2009)', 'Stroebe & Schut (1999)'],
  },
  {
    id: 'anger',
    name: '怒り',
    nameEn: 'Anger',
    category: 'basic',
    coreTheme: '不当な侵害・目標達成の阻害',
    triggers: [
      '列への割り込み、約束の不履行',
      '自分の意見を遮られる、不公平な扱い',
      '大切な人が傷つけられる',
      '道徳的・社会的不正義（義憤）',
      '故意性・不当性・制御可能性の知覚',
    ],
    process: [
      '扁桃体が「危険／不当」と高速分類',
      '視床下部からノルアドレナリン・コルチゾール放出',
      '交感神経の極端な優位',
      '行動傾向：接近的攻撃（恐怖の逃走と対照的）',
      '「カッとなる」「頭に血がのぼる」主観経験',
    ],
    bodyReactions: [
      '眉が下がり中央に寄る、唇の緊張',
      '心拍・血圧・体温の急上昇、顔の紅潮',
      '骨格筋への血流集中、拳を握る',
      '神経伝達物質：ノルアドレナリン、テストステロン上昇',
    ],
    function: '不当な侵害に対して相手の行動を変えさせる社会的交渉ツール。社会階層の維持と道徳的規範の強制。',
    transitions: [
      { to: 'frustration', label: '出口なし', type: 'INTENS' },
      { to: 'guilt', label: '自分の怒りへの後悔', type: 'APPR' },
      { to: 'contempt', label: '相手を格下と評価', type: 'APPR' },
      { to: 'sadness', label: '攻撃後の空虚', type: 'RESOLV' },
      { to: 'contentment', label: '鎮静・解決', type: 'RESOLV' },
    ],
    valence: -1, arousal: 2, dominance: 2,
    appraisal: { nov: 1, pleas: -1, goal: -2, cope: 1, norm: -2 },
    temporal: { onset: 1, peak: 2, decay: 15, persist: 2 },
    regulation: {
      adaptive: ['感情の言語化', '一時的な場の離脱', '身体的発散（運動）'],
      reappraisal: ['他者の意図の再評価（悪意でなく状況的要因）', '怒りのシグナルとしての理解'],
      contraindicated: ['感情の爆発的表出', '反芻的反復', 'アルコールによる抑制'],
    },
    references: ['Gross (1998)', 'Bushman (2002)'],
  },
  {
    id: 'fear',
    name: '恐怖',
    nameEn: 'Fear',
    category: 'basic',
    coreTheme: '即時的な身体的・心理的脅威',
    triggers: [
      'ヘビ・クモ・高所・暗闇（進化的に準備された刺激）',
      '急速に接近する物体、突然の大音響',
      '医師からの重大な告知',
      '事故・暴力の経験後の類似場面',
      '人前でのスピーチ直前',
    ],
    process: [
      'ローロード：視床→扁桃体（12ms以内の高速反応）',
      'ハイロード：大脳皮質経由の詳細評価',
      '視床下部・脳幹を介した即時の身体反応',
      '凍結→逃走→闘争→服従の行動選択',
      '意識化前に身体が動き始める',
    ],
    bodyReactions: [
      '眉の高い挙上と寄り、上瞼の大きな開大',
      '心拍急上昇、冷や汗、震え、立毛（鳥肌）',
      '瞳孔散大、口渇、過呼吸',
      '神経伝達物質：ノルアドレナリン、アドレナリン、コルチゾール急上昇',
    ],
    function: '脅威の即時検知と行動準備。生存に最も重要な適応感情のひとつ。',
    transitions: [
      { to: 'anxiety', label: '対象が曖昧・未来志向に', type: 'CHRONIC' },
      { to: 'anger', label: '脅威への反撃', type: 'APPR' },
      { to: 'relief', label: '脅威の消失', type: 'ACUTE' },
      { to: 'curiosity', label: '安全確認後の探索', type: 'RESOLV' },
    ],
    valence: -2, arousal: 2, dominance: -2,
    appraisal: { nov: 2, pleas: -2, goal: -2, cope: -2, norm: 0 },
    temporal: { onset: 0.2, peak: 0.5, decay: 20, persist: 1 },
    regulation: {
      adaptive: ['系統的脱感作', 'マインドフルな観察', '安全基地の確認'],
      reappraisal: ['脅威の現実的評価（確率・影響度の検討）', '対処資源の棚卸し'],
      contraindicated: ['恐怖対象の完全回避', '感情の無理な抑圧'],
    },
    references: ['LeDoux (1996)', 'Öhman & Mineka (2001)'],
  },
  {
    id: 'surprise',
    name: '驚き',
    nameEn: 'Surprise',
    category: 'basic',
    coreTheme: '予測の急激な不一致',
    triggers: [
      'サプライズパーティー',
      '意外な場所での知人との遭遇',
      '予想外の試験結果・展開',
      '突然の提案や宣告',
      '既知の場所での予期せぬ変化',
    ],
    process: [
      '感覚入力が予測モデルと不一致を起こす',
      '上丘・視床・前頭眼野が定位反射を起こす',
      '扁桃体・前帯状皮質が重要性を査定',
      '0.5〜2秒以内に次の感情へ遷移',
      '中性感情：続く評価によって色合いが決まる',
    ],
    bodyReactions: [
      '眉の高い挙上（眉間にしわなく）',
      '上瞼の大きな開大、口の楕円形の開き',
      '息の吸い込み、一過性の心拍上昇',
      '0.2〜0.5秒で立ち上がり急速に消失',
    ],
    function: '注意リソースを瞬時に外的事象に再配分する。新規情報への探索行動を準備する。',
    transitions: [
      { to: 'joy', label: '肯定的評価', type: 'ACUTE' },
      { to: 'fear', label: '否定的評価（脅威）', type: 'ACUTE' },
      { to: 'curiosity', label: '興味への転化', type: 'ACUTE' },
      { to: 'disgust', label: '不快な対象の認識', type: 'ACUTE' },
    ],
    valence: 0, arousal: 2, dominance: 0,
    appraisal: { nov: 2, pleas: 0, goal: 0, cope: 0, norm: 0 },
    temporal: { onset: 0.2, peak: 0.2, decay: 1, persist: 0.1 },
    regulation: {
      adaptive: ['一時停止と評価（立ち止まること）', '好奇心への転換'],
      reappraisal: ['驚きを情報として受け取る', '不確実性の受容'],
      contraindicated: ['即時的な過剰反応', '驚きの自動的な否定的解釈'],
    },
    references: ['Ekman (1972)'],
  },
  {
    id: 'disgust',
    name: '嫌悪',
    nameEn: 'Disgust',
    category: 'basic',
    coreTheme: '汚染への忌避',
    triggers: [
      '腐敗物・排泄物・嘔吐物の臭いや視覚',
      '食物への異物混入',
      '得体の知れないぬめり・腐臭',
      '近親相姦・残虐行為への道徳的嫌悪',
      '不潔に見える他者への対人嫌悪',
    ],
    process: [
      '島皮質前部が「汚染／忌避」と分類',
      '副交感神経の特殊反応（吐き気・唾液分泌増加）',
      '上唇が引き上げられ、鼻にしわ、舌の突出',
      '行動傾向：退避・吐き出し・洗浄',
    ],
    bodyReactions: [
      '上唇挙上、鼻のしわ、頬の挙上',
      '吐き気、唾液分泌、徐脈の場合あり',
      '「うっ」という発声、体のけいれん的な反応',
      '神経基盤：島皮質前部、扁桃体、眼窩前頭皮質',
    ],
    function: '病原体・腐敗物・感染リスクへの接触を避ける生物学的防御。道徳的嫌悪は社会規範の強化にも機能。',
    transitions: [
      { to: 'anger', label: '道徳的違反への怒りと混合', type: 'BLEND' },
      { to: 'contempt', label: '相手への持続的拒絶', type: 'CHRONIC' },
      { to: 'fear', label: '危険な汚染物への恐怖', type: 'BLEND' },
    ],
    valence: -2, arousal: 0, dominance: 1,
    appraisal: { nov: 0, pleas: -2, goal: -2, cope: 1, norm: -2 },
    temporal: { onset: 1, peak: 2, decay: 15, persist: 2 },
    regulation: {
      adaptive: ['対象からの物理的・心理的距離の確保', '道徳的嫌悪の批判的検討'],
      reappraisal: ['嫌悪の文化的相対性の認識', '過剰な道徳的嫌悪の再評価'],
      contraindicated: ['嫌悪対象への強制的な接触', '嫌悪感の極端な抑制'],
    },
    references: ['Rozin et al. (2008)'],
  },

  // ── ポジティブ感情 ────────────────────────────────────────────
  {
    id: 'love',
    name: '愛情・愛着',
    nameEn: 'Love / Attachment',
    category: 'positive',
    coreTheme: '特定の他者との深い絆と安全感',
    triggers: [
      '日々の小さな共有経験の累積',
      '辛いときに寄り添ってもらう',
      '相手が自分の話をよく聴いてくれる',
      '共に笑い・泣いた経験',
      '乳幼児期の応答的な養育者との相互作用',
    ],
    process: [
      '情熱期：ドーパミン・ノルアドレナリン優位（没頭・理想化）',
      '半年〜2年で愛着期へ移行',
      '愛着期：オキシトシン・バソプレシン優位（穏やかな絆）',
      '内的作業モデル（ボウルビィ）が形成され生涯持続',
    ],
    bodyReactions: [
      '対面時の心拍上昇、瞳孔散大',
      '別離時の胸の痛み（dACC活性）',
      '抱擁・接触時のオキシトシン放出',
      'C触覚線維による皮膚刺激が安心感を強化',
    ],
    function: '親密な人間関係・養育・長期的協力の基盤。愛着の安全基地が探索行動と回復力を支える。',
    transitions: [
      { to: 'joy', label: '相手との再会・共有', type: 'ACUTE' },
      { to: 'anxiety', label: '相手への心配', type: 'BLEND' },
      { to: 'jealousy', label: '関係の脅威', type: 'ACUTE' },
      { to: 'grief', label: '別離・死別', type: 'ACUTE' },
      { to: 'gratitude', label: '受け取った配慮への気づき', type: 'APPR' },
    ],
    valence: 2, arousal: 0, dominance: 0,
    appraisal: { nov: 0, pleas: 2, goal: 2, cope: 2, norm: 2 },
    temporal: { onset: 120, peak: 1440, decay: 100000, persist: 87600 },
    regulation: {
      adaptive: ['質の高い時間の共有', '感謝と愛着の表現', 'セキュアな愛着の育成'],
      reappraisal: ['愛着への恐れを安全として再評価', '脆弱性を強さとして認識'],
      contraindicated: ['完全な感情的依存', '依存の否定と壁の構築'],
    },
    references: ['Fisher (2004)', 'Bowlby (1969)', 'Gottman (1999)'],
  },
  {
    id: 'gratitude',
    name: '感謝',
    nameEn: 'Gratitude',
    category: 'positive',
    coreTheme: '他者の意図的配慮によって価値あるものが与えられた',
    triggers: [
      '見知らぬ人がドアを押さえてくれる',
      '深夜に友人が話を聴いてくれる',
      '家族が黙って好物を作ってくれていた',
      '困難時に上司がカバーしてくれる',
      '健康・自然・偶然の幸運への気づき',
    ],
    process: [
      '「これは当然ではない」という再評価',
      '価値・他者性・意図性・コスト性の知覚',
      '返礼動機の強化',
      '「胸が温かくなる」主観経験',
    ],
    bodyReactions: [
      '胸の温かみ、目の潤み',
      '身体の軽さ、肩の弛緩',
      '内側前頭前野・腹側線条体の活性化',
      'セロトニン・オキシトシン系の関与',
    ],
    function: '社会的互恵性のサイクルを起動する「社会的接着剤」。新しい関係を見つけ、既存の関係を強化し、絆を結ぶ（find-remind-bind）。',
    transitions: [
      { to: 'joy', label: '幸福感の増大', type: 'INTENS' },
      { to: 'love', label: '相手への愛着強化', type: 'INTENS' },
      { to: 'contentment', label: '穏やかな満足へ', type: 'RESOLV' },
      { to: 'elevation', label: '他者の善行への感動', type: 'APPR' },
    ],
    valence: 2, arousal: 0, dominance: 0,
    appraisal: { nov: 1, pleas: 2, goal: 1, cope: 2, norm: 2 },
    temporal: { onset: 5, peak: 10, decay: 120, persist: 6 },
    regulation: {
      adaptive: ['感謝日記', '感謝の手紙・言葉での表現', '恩恵の再想起'],
      reappraisal: ['「当然」から「贈りもの」への再認識', '互恵的つながりとしての関係の捉え直し'],
      contraindicated: ['感謝の義務化（負債感への変質）', '過小評価と見過ごし'],
    },
    references: ['McCullough et al. (2001)', 'Algoe (2012)', 'Emmons & McCullough (2003)'],
  },
  {
    id: 'pride',
    name: '誇り',
    nameEn: 'Pride',
    category: 'positive',
    coreTheme: '自己の達成を自分の能力・努力に帰属する',
    triggers: [
      '試験の合格、難しいプロジェクトの完遂',
      '自分の作品が評価される',
      '子どもが立派に育つ',
      '所属チームの勝利',
      '長期間の努力が実を結ぶ',
    ],
    process: [
      '①ポジティブな結果 ②自己への帰属 ③能力・努力への帰属',
      '運や他者の助けに帰属すれば誇りは弱く感謝が強まる',
      '「真正な誇り（自己の行為）」vs「傲慢な誇り（自己の存在）」',
    ],
    bodyReactions: [
      '胸を張る、頭を上げる（文化を超えて普遍的）',
      '両手を腰に当てる、両腕を高く上げる',
      '盲目の人にも同様の姿勢が観察される（生得的）',
    ],
    function: '社会的地位の交渉と維持。次の挑戦への継続的動機づけ。',
    transitions: [
      { to: 'joy', label: '達成の喜びと共存', type: 'BLEND' },
      { to: 'contempt', label: '過剰→傲慢', type: 'INTENS' },
      { to: 'shame', label: '他者に誇りを否定される', type: 'ACUTE' },
      { to: 'anxiety', label: '次も成功できるかの不安', type: 'APPR' },
    ],
    valence: 2, arousal: 1, dominance: 2,
    appraisal: { nov: 1, pleas: 2, goal: 2, cope: 2, norm: 1 },
    temporal: { onset: 10, peak: 30, decay: 120, persist: 24 },
    regulation: {
      adaptive: ['達成の言語化と共有', '適切な自己評価の維持', '他者への感謝との統合'],
      reappraisal: ['傲慢な誇りから真正な誇りへの転換', '成功の文脈的要因の認識'],
      contraindicated: ['自己誇大化', '達成の過小評価による誇りの抑圧'],
    },
    references: ['Tracy & Robins (2007)', 'Tracy & Matsumoto (2008)'],
  },
  {
    id: 'hope',
    name: '希望',
    nameEn: 'Hope',
    category: 'positive',
    coreTheme: '望ましい未来の可能性が不確実だが現実的に存在する',
    triggers: [
      '重病からの回復可能性の示唆',
      '長く取り組んだ目標に光が見え始める',
      '災害後に救援が届くという報せ',
      '子どもの未来を考えるとき',
      '春の訪れを感じる瞬間',
    ],
    process: [
      '絶望や悲しみの中から立ち上がる逆説的プロセス',
      '目標・経路（pathways）・主体性（agency）の3要素（スナイダー）',
      '「不確実性の中で行動を続ける」エネルギーの供給',
    ],
    bodyReactions: [
      '身体の軽さ、前向きの姿勢',
      '眼の輝き、声のトーン上昇',
      '行動の活性化、計画への集中',
    ],
    function: '不確実な状況下での目標追求行動の維持。否認と異なり、現実を見据えながら可能性を信じる。',
    transitions: [
      { to: 'joy', label: '目標達成', type: 'ACUTE' },
      { to: 'anxiety', label: '不確実性の増大', type: 'APPR' },
      { to: 'sadness', label: '希望の消失', type: 'ACUTE' },
      { to: 'curiosity', label: '可能性の探索', type: 'APPR' },
    ],
    valence: 1, arousal: 1, dominance: 0,
    appraisal: { nov: 1, pleas: 1, goal: 1, cope: 0, norm: 1 },
    temporal: { onset: 60, peak: 60, decay: 240, persist: 48 },
    regulation: {
      adaptive: ['具体的な行動計画の策定', 'サポートネットワークの活用', '小さな成功の積み上げ'],
      reappraisal: ['悲観的な予測の現実的修正', '「まだ可能性がある」という視点'],
      contraindicated: ['根拠のない楽観主義（否認）', '絶望的な思考の反芻'],
    },
    references: ['Snyder (1991)'],
  },
  {
    id: 'relief',
    name: '安心',
    nameEn: 'Relief',
    category: 'positive',
    coreTheme: '予期されたネガティブ結果の回避・ネガティブ状態の終了',
    triggers: [
      '検査結果が陰性だった',
      '行方不明の子どもが見つかった',
      '長い試験が終わった',
      '嵐が過ぎ去った',
      '予定の電車に間に合った',
    ],
    process: [
      'ストレスホルモンの急激な低下',
      '副交感神経の急速な賦活',
      '深い呼気を伴う身体の解放',
      '喜びとは異なる──ネガティブの消失',
    ],
    bodyReactions: [
      '「肩の荷が下りる」「ふっと力が抜ける」',
      '深い呼気、涙が出ることもある',
      'コルチゾールの急激な低下',
      '副交感神経の急速な優位化',
    ],
    function: 'ストレス耐性の回復と免疫機能の正常化。慢性的不安からの解放は喜びより深い身体的解放感を伴う。',
    transitions: [
      { to: 'joy', label: '回避の喜びへ', type: 'APPR' },
      { to: 'contentment', label: '静かな満足へ', type: 'RESOLV' },
      { to: 'gratitude', label: '助けてくれた人への感謝', type: 'APPR' },
    ],
    valence: 2, arousal: -1, dominance: 1,
    appraisal: { nov: 0, pleas: 2, goal: 2, cope: 2, norm: 1 },
    temporal: { onset: 2, peak: 3, decay: 30, persist: 3 },
    regulation: {
      adaptive: ['身体の弛緩を意識的に受け取る', '感謝とともに受容する'],
      reappraisal: ['脅威が去ったことの確認', '安全の現実的評価'],
      contraindicated: ['安心後の再不安への即時移行', '安堵の無視と緊張の継続'],
    },
    references: [],
  },
  {
    id: 'curiosity',
    name: '興味・好奇心',
    nameEn: 'Interest / Curiosity',
    category: 'positive',
    coreTheme: '適度な不確実性を持つ新規刺激への引きつけ',
    triggers: [
      '新しい本の最初のページ',
      '知らない街を歩く',
      '難解だが手がかりのあるパズル',
      '未知の料理の最初の一口',
      '講義中の思いがけない問い',
    ],
    process: [
      '「もう少しで理解できそう」な適度な不確実性',
      'ドーパミン系（黒質緻密部）と海馬の連携',
      '好奇心が高まった状態での記憶は無関係な情報まで定着しやすい',
      '探索行動の活性化',
    ],
    bodyReactions: [
      '前傾姿勢、眼の輝き、眉の軽い挙上',
      '集中と軽い興奮が共存',
      'ドーパミン放出による動機づけの高まり',
    ],
    function: '学習と探索の主要な動機。「拡張的好奇心」（新経験の追求）と「包摂的好奇心」（不確実性への耐性）の2種。',
    transitions: [
      { to: 'joy', label: '発見の喜び', type: 'ACUTE' },
      { to: 'awe', label: '巨大な謎への直面', type: 'INTENS' },
      { to: 'frustration', label: '理解が進まない', type: 'APPR' },
      { to: 'flow', label: 'スキルと難度が釣り合う', type: 'INTENS' },
    ],
    valence: 1, arousal: 1, dominance: 1,
    appraisal: { nov: 2, pleas: 1, goal: 1, cope: 1, norm: 1 },
    temporal: { onset: 3, peak: 5, decay: 30, persist: 2 },
    regulation: {
      adaptive: ['探索行動の継続', '問いの言語化', '不確実性の受容'],
      reappraisal: ['「分からない」を恐れではなく好機として捉える', '知的謙虚さの培養'],
      contraindicated: ['過度な情報収集（情報中毒）', '答えのない問いの回避'],
    },
    references: ['Gruber et al. (2014)', 'Kashdan (2009)'],
  },
  {
    id: 'awe',
    name: '畏敬',
    nameEn: 'Awe',
    category: 'positive',
    coreTheme: '広大さと世界観の更新の必要性',
    triggers: [
      'グランドキャニオン・満天の星空・巨大な仏像',
      '出産への立ち合い',
      'クラシック音楽の終楽章',
      '深い知的洞察を得た瞬間',
      '聖人の行為・英雄的自己犠牲の目撃',
    ],
    process: [
      '広大さ（vastness）の知覚',
      '既存の心の枠組みを超える体験（適応の必要性）',
      'デフォルト・モード・ネットワークの活動低下',
      '自己の縮小感（small selfness）',
    ],
    bodyReactions: [
      '時間知覚の伸長（時間がゆっくり流れる）',
      '鳥肌、涙、開いた口、動きの停止',
      '胸の広がり感、身体の軽さ',
    ],
    function: '①謙虚さの増加 ②向社会的行動の促進 ③物質主義の減少 ④自然との一体感。瞑想・サイケデリック体験と部分的に共通の神経基盤。',
    transitions: [
      { to: 'joy', label: '美しさへの共鳴', type: 'BLEND' },
      { to: 'curiosity', label: '謎への探索意欲', type: 'APPR' },
      { to: 'gratitude', label: '存在への感謝', type: 'APPR' },
      { to: 'contentment', label: '静謐な満足へ', type: 'RESOLV' },
    ],
    valence: 2, arousal: 0, dominance: -2,
    appraisal: { nov: 2, pleas: 2, goal: 0, cope: -1, norm: 1 },
    temporal: { onset: 5, peak: 10, decay: 60, persist: 8 },
    regulation: {
      adaptive: ['自然・芸術・人間の偉大さへの意図的な露出', '畏敬の体験の記録と想起'],
      reappraisal: ['自己の小ささを脅威でなく解放として捉える', '謙虚さを強みとして認識'],
      contraindicated: ['すべてを説明・制御しようとする強迫的な傾向'],
    },
    references: ['Keltner & Haidt (2003)'],
  },
  {
    id: 'flow',
    name: 'フロー',
    nameEn: 'Flow',
    category: 'positive',
    coreTheme: '課題難度とスキルが釣り合った完全な活動没入',
    triggers: [
      'スポーツ・演奏・執筆・プログラミングでの没入',
      '課題の難度と自分のスキルが絶妙に釣り合う状況',
      '即時フィードバックがある明確な目標',
      '外的報酬のない純粋な活動そのものへの動機',
    ],
    process: [
      '意識から自己が消える（loss of self-consciousness）',
      '時間感覚の変容（速く/遅く感じる）',
      '行為と結果が直接結びついて感じられる',
      'ノルアドレナリン・ドーパミン・エンドルフィン・アナンダミドの複合放出',
    ],
    bodyReactions: [
      '時間感覚の歪み',
      '疲労感の消失（没入中）',
      '終了後の深い充実感と疲労の混合',
    ],
    function: '熟達と意味の源泉。「最適経験」として人生の質を高める。内発的動機づけの頂点。',
    transitions: [
      { to: 'joy', label: '活動後の達成感', type: 'RESOLV' },
      { to: 'contentment', label: '深い満足へ', type: 'RESOLV' },
      { to: 'pride', label: '自己の成長の認識', type: 'APPR' },
    ],
    valence: 2, arousal: 1, dominance: 2,
    appraisal: { nov: 1, pleas: 2, goal: 2, cope: 2, norm: 1 },
    temporal: { onset: 300, peak: 60, decay: 30, persist: 2 },
    regulation: {
      adaptive: ['挑戦-スキルバランスの調整', '外的妨害の排除', '明確な目標の設定'],
      reappraisal: ['活動そのものへの内発的価値の発見', '結果ではなく過程への集中'],
      contraindicated: ['過度な外的評価・報酬の強調', '活動中の自己観察・批判'],
    },
    references: ['Csikszentmihalyi (1990)'],
  },
  {
    id: 'elevation',
    name: '高揚',
    nameEn: 'Elevation',
    category: 'positive',
    coreTheme: '他者の道徳的に美しい行為の目撃',
    triggers: [
      '他者の英雄的・献身的行為を目撃する',
      '見知らぬ人が困っている人を助ける場面',
      '感動的なドキュメンタリー・実話',
      '自己犠牲の精神の発露',
    ],
    process: [
      '他者の善行の認知的評価',
      '迷走神経の活性化（HRV上昇）',
      'オキシトシン放出',
      '「自分も善い行いをしたい」という動機の発生',
    ],
    bodyReactions: [
      '胸が温かく開く感覚',
      '涙が出そうになる',
      '鳥肌、声のつまり',
    ],
    function: '道徳的模倣行動の促進。向社会的行動の連鎖を起こす。共同体の道徳的水準の向上。',
    transitions: [
      { to: 'gratitude', label: '恩恵への感謝', type: 'APPR' },
      { to: 'awe', label: '人間の崇高さへの畏敬', type: 'INTENS' },
      { to: 'joy', label: '感動の喜びへ', type: 'BLEND' },
    ],
    valence: 2, arousal: 0, dominance: 0,
    appraisal: { nov: 1, pleas: 2, goal: 1, cope: 2, norm: 2 },
    temporal: { onset: 5, peak: 5, decay: 30, persist: 6 },
    regulation: {
      adaptive: ['高揚体験の共有と語り', '道徳的行動への実践移行'],
      reappraisal: ['感動を動機として活用する', '他者の善性への信頼の強化'],
      contraindicated: ['偽善・演技的な感情表出', '感動の商業的・操作的利用'],
    },
    references: ['Haidt (2003)'],
  },
  {
    id: 'contentment',
    name: '静謐・満足',
    nameEn: 'Serenity / Contentment',
    category: 'positive',
    coreTheme: 'すべてが満たされ、何も足したくも引きたくもない',
    triggers: [
      '夕暮れに縁側で温かいお茶を飲む',
      '子どもが眠った後の静かな部屋',
      '長い旅の終わりに自宅に着く',
      '自然の中でのゆったりとした時間',
      '親しい人との沈黙の共有',
    ],
    process: [
      '低覚醒・高ヴァレンスの感情状態',
      '副交感神経の穏やかな優位',
      '「足るを知る」状態の認知',
    ],
    bodyReactions: [
      '筋肉の完全な弛緩',
      '呼吸の深さと遅さ',
      '胸の穏やかな温かみ',
    ],
    function: '持続的幸福の基盤。東洋的な「侘び寂び」「足るを知る」の感性と親和性が高い。興奮を伴う喜びとは対照的。',
    transitions: [
      { to: 'joy', label: '刺激による活性化', type: 'ACUTE' },
      { to: 'boredom', label: '刺激の不足', type: 'APPR' },
    ],
    valence: 2, arousal: -2, dominance: 1,
    appraisal: { nov: -1, pleas: 2, goal: 2, cope: 2, norm: 2 },
    temporal: { onset: 120, peak: 120, decay: 120, persist: 12 },
    regulation: {
      adaptive: ['マインドフルネス', '現在への注意の向け直し', '単純な喜びの味わい'],
      reappraisal: ['「十分である」という認知の強化', '比較による欠乏感からの離脱'],
      contraindicated: ['絶え間ない刺激追求', '現在への退屈や不満の増幅'],
    },
    references: [],
  },

  // ── ネガティブ感情 ────────────────────────────────────────────
  {
    id: 'anxiety',
    name: '不安',
    nameEn: 'Anxiety',
    category: 'negative',
    coreTheme: '制御不能な未来の脅威と待機時間',
    triggers: [
      '明日のプレゼンの前夜',
      '検査結果を待つ数日間',
      '将来の仕事・経済的見通しの不透明さ',
      '恋人の気持ちが読めないとき',
      '「何か忘れている気がする」状態',
    ],
    process: [
      'BNST（分界条床核）と扁桃体の持続的活性化',
      '前頭前野での「もしも」のシミュレーション反復',
      'HPA軸の慢性的賦活',
      '脅威情報への選択的注意→回避行動→短期的安心→長期的増強の悪循環',
    ],
    bodyReactions: [
      '「胸がざわつく」「落ち着かない」「考えが止まらない」',
      '心拍上昇、筋緊張（肩・首・顎）、浅い呼吸',
      '消化機能低下、睡眠障害',
      'HRV（心拍変動性）の低下',
    ],
    function: '危険への準備と計画行動の促進（適応的機能）。過剰になると回避の悪循環を生む。',
    transitions: [
      { to: 'fear', label: '対象が具体化・即時化', type: 'ACUTE' },
      { to: 'frustration', label: '行動できない焦り', type: 'BLEND' },
      { to: 'relief', label: '脅威の消失', type: 'RESOLV' },
      { to: 'sadness', label: '慢性化→抑うつへ', type: 'CHRONIC' },
      { to: 'hope', label: '可能性の認識', type: 'APPR' },
    ],
    valence: -2, arousal: 1, dominance: -2,
    appraisal: { nov: 2, pleas: -2, goal: -1, cope: -2, norm: 0 },
    temporal: { onset: 30, peak: 60, decay: 180, persist: 72 },
    regulation: {
      adaptive: ['腹式呼吸・漸進的筋弛緩法', '不確実性の受容（ACT）', '暴露と反応阻止'],
      reappraisal: ['脅威の現実的確率の検討', '「最悪の場合」の具体的対処計画の策定'],
      contraindicated: ['回避行動', '安全確認行動の過剰', '完全なコントロール追求'],
    },
    references: ['Spielberger (1983)'],
  },
  {
    id: 'grief',
    name: '悲嘆',
    nameEn: 'Grief',
    category: 'negative',
    coreTheme: '重大な喪失に対する長期の複合的反応',
    triggers: [
      '配偶者・近親者の死',
      '長期にわたる離別',
      '健康喪失・重大な障害の発生',
      '故郷・家の喪失',
      '長く続けてきた役割の終焉',
    ],
    process: [
      '悲しみ・怒り・罪悪感・不安・安堵・無感覚が波状に繰り返す',
      '「喪失志向」と「回復志向」のあいだを振り子のように行き来する（二重過程モデル）',
      '「統合的悲嘆」：喪失を人生の物語に組み込み新生活を営む状態',
    ],
    bodyReactions: [
      '急性期：強烈な胸の痛み、現実感の喪失',
      '慢性期：疲労、食欲不振、免疫低下',
      '思い出の手がかりによる再燃',
    ],
    function: '喪失への長期的適応。故人との「continuing bonds（持続する絆）」を維持しながら新しい生活を構築する過程。',
    transitions: [
      { to: 'sadness', label: '急性の悲しみ', type: 'BLEND' },
      { to: 'anger', label: '運命・自分への怒り', type: 'BLEND' },
      { to: 'guilt', label: '「もっとできた」という後悔', type: 'BLEND' },
      { to: 'anxiety', label: '残された生活への不安', type: 'BLEND' },
      { to: 'contentment', label: '統合・受容', type: 'RESOLV' },
      { to: 'nostalgia', label: '故人への温かい記憶', type: 'APPR' },
    ],
    valence: -2, arousal: -1, dominance: -2,
    appraisal: { nov: 0, pleas: -2, goal: -2, cope: -2, norm: 1 },
    temporal: { onset: 120, peak: 1440, decay: 20160, persist: 8760 },
    regulation: {
      adaptive: ['悲嘆の言語化・語り', 'グリーフサポートグループ', '故人との象徴的つながりの維持'],
      reappraisal: ['喪失を意味のある体験として統合する', '継続する絆の形式の変容'],
      contraindicated: ['悲嘆の抑圧と「立ち直り」の強制', '孤立', '自己批判の反芻'],
    },
    references: ['Bonanno (2009)', 'Stroebe & Schut (1999)'],
  },
  {
    id: 'disappointment',
    name: '失望',
    nameEn: 'Disappointment',
    category: 'negative',
    coreTheme: '期待していたポジティブな結果が得られなかった',
    triggers: [
      '採用結果が不採用',
      '楽しみにしていたイベントの中止',
      '信頼していた人の裏切り',
      '長く準備した試験での不振',
      '期待していた出来事が平凡だった',
    ],
    process: [
      '期待→結果の確認→負の予測誤差→失望',
      '「期待が高すぎた」vs「現実が悪かった」の帰属',
      '自責または他責の認知が遷移先を決める',
    ],
    bodyReactions: [
      '肩を落とす、ため息',
      '軽い胸の重さ、エネルギー低下',
      '声のトーン低下、表情の曇り',
    ],
    function: '期待の現実への調整。再挑戦か方向転換かの動機づけを決定する分岐点。',
    transitions: [
      { to: 'sadness', label: '受容ルート', type: 'APPR' },
      { to: 'anger', label: '他責ルート', type: 'APPR' },
      { to: 'shame', label: '自責ルート', type: 'APPR' },
      { to: 'hope', label: '再挑戦への動機', type: 'APPR' },
    ],
    valence: -1, arousal: -1, dominance: -1,
    appraisal: { nov: -1, pleas: -1, goal: -2, cope: -1, norm: 0 },
    temporal: { onset: 5, peak: 10, decay: 60, persist: 12 },
    regulation: {
      adaptive: ['期待の現実的な再設定', '失望から得た情報の活用', '他者への感情表現'],
      reappraisal: ['失望を情報として扱う（期待のキャリブレーション）', '選択肢の再評価'],
      contraindicated: ['「どうせ何をやってもダメ」という一般化', '関係そのものの否定'],
    },
    references: [],
  },
  {
    id: 'regret',
    name: '後悔',
    nameEn: 'Regret',
    category: 'negative',
    coreTheme: '別の選択をしていればより良かったという反事実的思考',
    triggers: [
      '転職の機会を逃した記憶',
      '別れた相手を思い出す',
      '若いときに勉強しなかった後悔',
      '言ってしまった言葉を取り消したい',
      '長期的な不行為への悔い（「やればよかった」）',
    ],
    process: [
      '想起→反事実シミュレーション（「もし〜なら」）',
      '短期的：行為の後悔が強い',
      '長期的：不行為の後悔が深く持続する（ギロビッチ）',
      '自責の反芻vs学習への転換の分岐',
    ],
    bodyReactions: [
      '胸の重さ、頭を抱える',
      '過去の場面の反復的な想起',
      'ため息、ゆっくりとした動作',
    ],
    function: '適切に処理されれば意思決定の学習機能を果たす。反芻に陥ると慢性的抑うつへ変質。',
    transitions: [
      { to: 'sadness', label: '喪失感', type: 'BLEND' },
      { to: 'shame', label: '自己全体への批判', type: 'APPR' },
      { to: 'guilt', label: '行為への批判', type: 'APPR' },
      { to: 'hope', label: '学習→改善への動機', type: 'APPR' },
      { to: 'contentment', label: '受容・意味の発見', type: 'RESOLV' },
    ],
    valence: -1, arousal: -1, dominance: -1,
    appraisal: { nov: 0, pleas: -1, goal: -1, cope: -1, norm: -1 },
    temporal: { onset: 60, peak: 120, decay: 1440, persist: 720 },
    regulation: {
      adaptive: ['後悔から学べる教訓の明確化', 'セルフ・コンパッション', '「これからできること」への集中'],
      reappraisal: ['後悔を自己批判でなく学習の素材として見る', '過去の自分の状況的制約の認識'],
      contraindicated: ['反芻的な後悔の反復', '自己罰的な思考', '「タラレバ」の過度な展開'],
    },
    references: ['Gilovich & Medvec (1995)', 'Ware (2011)'],
  },
  {
    id: 'boredom',
    name: '退屈',
    nameEn: 'Boredom',
    category: 'negative',
    coreTheme: '意味も興味もない状況からの脱出不能',
    triggers: [
      '長い会議、退屈な授業',
      '繰り返しの単調作業',
      '何もない雨の日曜日',
      '退職・入院中の長い時間',
      '「したいことがあるのに何をしたいか分からない」状態',
    ],
    process: [
      '現在の活動への注意維持困難',
      '時間知覚の伸長（時間がゆっくり）',
      'デフォルト・モード・ネットワークの活発化',
      'マインドワンダリングの増大',
    ],
    bodyReactions: [
      'あくび、うつろな視線',
      '姿勢の崩れ、頭を支える',
      '軽い苛立ち、眠気',
    ],
    function: '①新規性・意味への動機づけ ②マインドワンダリングによる創造的洞察の孵化。退屈耐性の低さは多くの依存症・衝動性と相関。',
    transitions: [
      { to: 'curiosity', label: 'マインドワンダリング→洞察', type: 'APPR' },
      { to: 'frustration', label: 'イライラの増大', type: 'INTENS' },
      { to: 'contentment', label: '意味の発見・受容', type: 'RESOLV' },
    ],
    valence: -1, arousal: -2, dominance: -1,
    appraisal: { nov: -2, pleas: -1, goal: -1, cope: 0, norm: 0 },
    temporal: { onset: 300, peak: 60, decay: 60, persist: 4 },
    regulation: {
      adaptive: ['意味のある活動への転換', '好奇心への意図的な向き直し', 'マインドワンダリングの活用'],
      reappraisal: ['退屈を創造的思考の種床として見る', '「今ここ」への気づき'],
      contraindicated: ['スマートフォンへの即時逃避', '過度な刺激追求', '退屈感の徹底的な排除'],
    },
    references: ['Mann & Cadman (2014)'],
  },
  {
    id: 'loneliness',
    name: '寂しさ',
    nameEn: 'Loneliness',
    category: 'negative',
    coreTheme: 'つながりの質と量が期待に届いていない',
    triggers: [
      'パーティーで誰とも話せなかった夜',
      '引っ越し直後・単身赴任',
      '定年退職後・伴侶との死別後',
      'SNSで他者の楽しそうな投稿を見る',
      '自分のことを本当に分かってくれる人がいないと感じる',
    ],
    process: [
      '客観的孤立（social isolation）と主観的寂しさは別物',
      '「飢え」「渇き」と同様の生物学的シグナル（カチオッポ）',
      '警戒過剰・他者への不信→孤立を深める悪循環',
    ],
    bodyReactions: [
      '胸の空洞感、身体の重さ',
      '睡眠障害、免疫機能低下',
      '慢性炎症マーカーの上昇',
    ],
    function: '社会的つながりの修復への動機づけ。慢性化すると喫煙15本/日に匹敵する死亡リスク上昇（ホルト＝ルンスタッド）。',
    transitions: [
      { to: 'sadness', label: '喪失感', type: 'BLEND' },
      { to: 'anxiety', label: '孤立への恐怖', type: 'BLEND' },
      { to: 'anger', label: '他者への不満', type: 'APPR' },
      { to: 'love', label: 'つながりの回復', type: 'RESOLV' },
    ],
    valence: -2, arousal: -1, dominance: -1,
    appraisal: { nov: 0, pleas: -2, goal: -2, cope: -1, norm: 1 },
    temporal: { onset: 1440, peak: 10080, decay: 10080, persist: 8760 },
    regulation: {
      adaptive: ['小さなつながりの積み重ね（挨拶・雑談）', '共通の関心事を持つグループへの参加', 'セルフ・コンパッション'],
      reappraisal: ['孤独と孤立の区別', '社会的警戒の認識と修正'],
      contraindicated: ['さらなる孤立化', 'SNSの過剰利用', '他者への不信の強化'],
    },
    references: ['Cacioppo & Patrick (2008)', 'Holt-Lunstad et al. (2015)'],
  },
  {
    id: 'frustration',
    name: '焦燥',
    nameEn: 'Frustration / Agitation',
    category: 'negative',
    coreTheme: '目標達成が阻害されているが対処手段が見えない',
    triggers: [
      '締切が迫っているのに作業が進まない',
      '渋滞のなかで身動きが取れない',
      '子どもが言うことを聞かない',
      'パソコンが固まった',
      '議論で言いたいことが言葉にならない',
    ],
    process: [
      '目標阻害の知覚＋対処手段の不在',
      '交感神経の急激な高まり',
      '制御不能感の二次的不安',
      '衝動的行動への傾き',
    ],
    bodyReactions: [
      '貧乏ゆすり、深いため息、徘徊',
      '身体のそわそわ感、筋肉の緊張',
      '短気な反応傾向、声のとがり',
    ],
    function: '目標阻害への警報シグナル。問題への集中エネルギーを供給するが、暴走すると対人関係を損なう。',
    transitions: [
      { to: 'anger', label: '対象への怒りへ', type: 'INTENS' },
      { to: 'anxiety', label: '慢性的な制御不能感', type: 'CHRONIC' },
      { to: 'boredom', label: '諦め・投げやり', type: 'APPR' },
      { to: 'contentment', label: '問題解決・受容', type: 'RESOLV' },
    ],
    valence: -1, arousal: 2, dominance: 0,
    appraisal: { nov: 0, pleas: -1, goal: -2, cope: -1, norm: 0 },
    temporal: { onset: 10, peak: 5, decay: 20, persist: 1 },
    regulation: {
      adaptive: ['目標の再分解（小さなステップへ）', '一時的な離脱と休憩', '問題の言語化'],
      reappraisal: ['障害を挑戦として再定義', '状況の制御可能な側面への集中'],
      contraindicated: ['衝動的な行動化', '怒りの他者への向け直し', '諦めによる完全放棄'],
    },
    references: [],
  },
  {
    id: 'nostalgia',
    name: 'ノスタルジア',
    nameEn: 'Nostalgia',
    category: 'negative',
    coreTheme: '過去への温かい切望と喪失感の混合（二価感情）',
    triggers: [
      '懐かしい音楽・匂い・写真',
      '故郷や学校を思い出す',
      '昔の友人との再会',
      '子どもの頃の場所を訪れる',
      '古いアルバムを開く',
    ],
    process: [
      '過去の記憶の想起（嗅覚は特に強く直結）',
      '「温かさ」と「切なさ」の同時経験',
      '自己連続性の強化（過去と現在の自己をつなぐ）',
    ],
    bodyReactions: [
      '胸の甘い痛み',
      '目の潤み、微笑みと悲しみの混合表情',
      '時間知覚の変容（過去が身近に感じる）',
    ],
    function: '自己連続性の維持。精神的健康に対して保護的に働く（セディキデスら）。孤独感・不安への解毒剤。',
    transitions: [
      { to: 'sadness', label: '喪失感の強調', type: 'APPR' },
      { to: 'joy', label: '温かい記憶の強調', type: 'APPR' },
      { to: 'gratitude', label: '過去への感謝', type: 'APPR' },
      { to: 'love', label: '関係への思い', type: 'BLEND' },
    ],
    valence: 0, arousal: -1, dominance: 0,
    appraisal: { nov: 0, pleas: 1, goal: 0, cope: 1, norm: 1 },
    temporal: { onset: 10, peak: 10, decay: 60, persist: 3 },
    regulation: {
      adaptive: ['懐かしい記憶を人生の資源として活用', '現在との橋渡しとしての回想'],
      reappraisal: ['過去を美化でなく資源として活用', '現在にも価値があることへの注意'],
      contraindicated: ['過去への逃避・現実逃避としての利用', '「昔はよかった」という現在の否定'],
    },
    references: ['Sedikides et al. (2015)'],
  },

  // ── 社会的感情 ────────────────────────────────────────────────
  {
    id: 'jealousy',
    name: '嫉妬',
    nameEn: 'Jealousy',
    category: 'social',
    coreTheme: '大切な関係を第三者に奪われる脅威（三者関係）',
    triggers: [
      '恋人がスマートフォンで誰かと頻繁にやりとりしている',
      '配偶者が同僚の名前を頻繁に出す',
      '子どもが自分より他の親に懐いている',
      'メンターが新しい弟子を可愛がる',
      '不確実性（はっきりしないからこそ強まる）',
    ],
    process: [
      '関係の特別さへの脅威認知',
      '「あの人と自分どちらが大切か」という比較',
      '恐怖・怒り・悲しみの混合',
      '監視・確認・支配・退避の行動傾向',
    ],
    bodyReactions: [
      '胸の締めつけ、不快な興奮',
      '監視行動の増大、確認衝動',
      'コルチゾール上昇、睡眠障害',
    ],
    function: '配偶関係・重要な絆の保護（進化的機能）。過剰になれば関係そのものを破壊する逆説的危険性をもつ。',
    transitions: [
      { to: 'anger', label: '確信→攻撃的行動', type: 'APPR' },
      { to: 'anxiety', label: '不確実な疑念の持続', type: 'CHRONIC' },
      { to: 'sadness', label: '喪失の受け入れ', type: 'RESOLV' },
      { to: 'shame', label: '嫉妬する自分への嫌悪', type: 'APPR' },
    ],
    valence: -2, arousal: 1, dominance: -1,
    appraisal: { nov: 1, pleas: -2, goal: -2, cope: -1, norm: 0 },
    temporal: { onset: 30, peak: 30, decay: 120, persist: 24 },
    regulation: {
      adaptive: ['パートナーとの率直な対話', '自己の不安の根源の探索', '信頼関係の構築'],
      reappraisal: ['嫉妬を愛着の強さのシグナルとして捉える', '確認行動の効果の批判的評価'],
      contraindicated: ['過度な監視・確認行動', '関係の独占的コントロール', '自己開示の回避'],
    },
    references: [],
  },
  {
    id: 'envy',
    name: '羨望',
    nameEn: 'Envy',
    category: 'social',
    coreTheme: '他者が自分の持っていないものを持っている（二者関係）',
    triggers: [
      '同期入社の同僚が先に昇進した',
      'SNSで友人の充実した生活を見る',
      '兄弟姉妹の境遇との比較',
      '同年代の人の結婚・出産・成功の報告',
      '自分の達成できない分野での他者の成功',
    ],
    process: [
      '「他者は持っているが自分は持っていない」という比較',
      '建設的羨望（benign envy）：「自分も得たい」上向きの動機',
      '悪意ある羨望（malicious envy）：「相手のものを壊したい」破壊的動機',
      '達成可能性の知覚が建設的/破壊的の分岐を決める',
    ],
    bodyReactions: [
      '胸の苦い感覚、顎の緊張',
      '対象の回避または執着',
      'モチベーションの変化（上昇または低下）',
    ],
    function: '（建設的羨望）自己改善への動機づけ。（悪意ある羨望）社会的不平等への反応。多くの文化で道徳的に否定され、表出が抑制される。',
    transitions: [
      { to: 'anger', label: '悪意ある羨望→攻撃', type: 'APPR' },
      { to: 'sadness', label: '自己の不足感', type: 'APPR' },
      { to: 'hope', label: '建設的羨望→目標設定', type: 'APPR' },
      { to: 'shame', label: '羨む自分への嫌悪', type: 'APPR' },
    ],
    valence: -1, arousal: 0, dominance: -1,
    appraisal: { nov: 0, pleas: -1, goal: -1, cope: -1, norm: -1 },
    temporal: { onset: 60, peak: 60, decay: 120, persist: 12 },
    regulation: {
      adaptive: ['羨望を目標設定のシグナルとして活用', '自己の強みと価値の再確認', '比較対象との関係再構築'],
      reappraisal: ['他者の成功を「パイの独占」でなく「可能性の実証」として捉える', 'ゼロサムでない人生観の採用'],
      contraindicated: ['SNS上の比較の反復', '他者の毀損・妨害', '自己嫌悪への沈潜'],
    },
    references: ['van de Ven et al. (2009)'],
  },
  {
    id: 'shame',
    name: '恥',
    nameEn: 'Shame',
    category: 'social',
    coreTheme: '自己という存在そのものが悪い・欠陥があるという評価',
    triggers: [
      '失敗を他者に目撃される',
      '自分の弱みを露呈してしまう',
      '容姿・体重・出自で軽蔑される',
      '他者の前で泣いてしまう',
      '虐待・いじめの経験',
    ],
    process: [
      '他者の視線（実在または想像）下での自己全体への否定的評価',
      '「私はダメな人間だ」（行為ではなく存在への帰属）',
      '視線回避・身体の縮こまり・赤面・発汗',
      '逃避・隠蔽・攻撃のいずれかの行動傾向',
    ],
    bodyReactions: [
      '赤面（顔・首・耳）、視線の回避',
      '身体の縮こまり（自己を小さく見せる）',
      '胸の締めつけ、頭を垂れる',
    ],
    function: '社会規範の内面化と維持（自己意識感情）。過剰な恥は隠蔽・孤立・抑うつ・薬物依存へのリスク。恥への耐性（shame resilience）が回復の鍵。',
    transitions: [
      { to: 'anger', label: '他者への投影・攻撃', type: 'APPR' },
      { to: 'sadness', label: '自己嫌悪→抑うつ', type: 'CHRONIC' },
      { to: 'anxiety', label: '再曝露への恐れ', type: 'BLEND' },
      { to: 'guilt', label: '自己→行為への評価転換', type: 'APPR' },
    ],
    valence: -2, arousal: 0, dominance: -2,
    appraisal: { nov: 1, pleas: -2, goal: -2, cope: -2, norm: -2 },
    temporal: { onset: 1, peak: 2, decay: 30, persist: 4 },
    regulation: {
      adaptive: ['恥の脆弱性の言語化（ブラウン）', 'セルフ・コンパッション', '信頼できる他者への開示'],
      reappraisal: ['行為と存在の分離（「ダメな行為」≠「ダメな人間」）', '恥を共通人間性の一部として捉える'],
      contraindicated: ['完全な隠蔽と孤立', '恥の反芻的反復', '恥を攻撃性に転化'],
    },
    references: ['Tangney et al. (2003)', 'Brown (2012)'],
  },
  {
    id: 'guilt',
    name: '罪悪感',
    nameEn: 'Guilt',
    category: 'social',
    coreTheme: '自分の行為が悪かったという評価',
    triggers: [
      '約束を破ったとき',
      '嘘をついたとき',
      '他者を傷つけたとき',
      '介護を十分にできなかったと感じる',
      '亡くなった人にもっとできたことがあると思う',
    ],
    process: [
      '「私はダメなことをした」（行為への帰属）',
      '他者への害の認識と責任の自己帰属',
      '修復・謝罪・補償への強い動機',
      '過剰な罪悪感→自罰の反芻→抑うつ',
    ],
    bodyReactions: [
      '胸の重さ、落ち着かなさ',
      '胃の不快感、食欲低下',
      '視線を外しやすいが逃げ隠れはしない（恥との違い）',
    ],
    function: '適切に処理されれば謝罪→修復→関係強化の建設的サイクルを生む。過剰・慢性化は抑うつへ変質。',
    transitions: [
      { to: 'sadness', label: '修復不能な場合', type: 'CHRONIC' },
      { to: 'shame', label: '行為→自己全体への帰属転換', type: 'APPR' },
      { to: 'relief', label: '謝罪・修復後', type: 'RESOLV' },
      { to: 'gratitude', label: '赦しを受けた後', type: 'APPR' },
    ],
    valence: -1, arousal: 0, dominance: -1,
    appraisal: { nov: 0, pleas: -1, goal: -1, cope: 0, norm: -2 },
    temporal: { onset: 30, peak: 60, decay: 120, persist: 48 },
    regulation: {
      adaptive: ['謝罪・修復行動', '再発防止の具体的計画', '赦しの探索（自己赦しを含む）'],
      reappraisal: ['「取り返せる罪」と「取り返せない罪」の区別', '自罰の代わりに修復へのエネルギー転換'],
      contraindicated: ['自罰的反芻', '関係の一方的な断絶', '謝罪なしの自己赦し'],
    },
    references: ['Tangney et al. (2003)'],
  },
  {
    id: 'empathy',
    name: '共感',
    nameEn: 'Empathy',
    category: 'social',
    coreTheme: '他者の感情・視点・苦痛を理解・共有する',
    triggers: [
      '泣いている人を見る',
      '苦しんでいる他者の話を聴く',
      '映画・小説の登場人物の境遇',
      '他者の表情・声・身体言語の観察',
    ],
    process: [
      '情動的共感（自動的・身体的な感じ取り）：ミラーニューロン系',
      '認知的共感（視点取得・心の理論）：内側前頭前野・TPJ',
      '共感的関心（compassion）：苦痛を和らげたい動機',
      '情動的共感の過剰→共感疲労→燃え尽き',
    ],
    bodyReactions: [
      '胸の痛み、目の潤み',
      '表情・声の同期（情動伝染）',
      '身体的な「共鳴」',
    ],
    function: '他者理解と向社会的行動の基盤。情動的共感→共感疲労、共感的関心→持続的向社会行動という区別が重要。',
    transitions: [
      { to: 'sadness', label: '他者の悲しみの共有', type: 'BLEND' },
      { to: 'love', label: '深い他者理解からの絆', type: 'INTENS' },
      { to: 'elevation', label: '感動的な善行の目撃', type: 'APPR' },
      { to: 'frustration', label: '共感疲労', type: 'CHRONIC' },
    ],
    valence: 0, arousal: 0, dominance: 0,
    appraisal: { nov: 0, pleas: 0, goal: 0, cope: 0, norm: 1 },
    temporal: { onset: 5, peak: 5, decay: 30, persist: 2 },
    regulation: {
      adaptive: ['情動的共感と認知的共感のバランス調整', 'セルフ・コンパッション', '共感の境界設定'],
      reappraisal: ['他者の苦痛を感じながら自己を保つ（ケア疲れの予防）', '共感を燃料でなく情報として使う'],
      contraindicated: ['他者の感情の引き受けすぎ', '自己の感情の無視', '強制的な共感の表現'],
    },
    references: ['Decety & Jackson (2004)', 'Singer & Klimecki (2014)'],
  },
  {
    id: 'embarrassment',
    name: '困惑・気まずさ',
    nameEn: 'Embarrassment',
    category: 'social',
    coreTheme: '社会的場面での予期せぬ目立ち（軽度・短時間）',
    triggers: [
      '人前で転ぶ',
      'ファスナーが開いていたと指摘される',
      '名前を間違える',
      '予期せぬ場所で知人に出くわす',
      '誤って他人に「お母さん」と呼びかける',
    ],
    process: [
      '「自分が公の前で予期せず目立ってしまった」認知',
      '恥と異なり自己の本質への評価ではない',
      '通常は短時間（数秒〜数分）で消失',
      '身体的反応が非常に速く（0.5〜1秒）立ち上がる',
    ],
    bodyReactions: [
      '赤面（顔・首・耳まで）、視線回避',
      'ぎこちない笑い、頭を掻く、口を覆う',
      '身体の縮こまり',
    ],
    function: '「私はあなたの規範を知っており、違反を認めている」という宥和シグナル。困惑を上手く表出する人は失敗にもかかわらず好感を持たれやすい。',
    transitions: [
      { to: 'shame', label: '自己否定が加わる', type: 'INTENS' },
      { to: 'joy', label: '笑いへの転化', type: 'APPR' },
      { to: 'anger', label: '指摘した相手への怒り', type: 'APPR' },
    ],
    valence: -1, arousal: 1, dominance: -1,
    appraisal: { nov: 1, pleas: -1, goal: -1, cope: 0, norm: -1 },
    temporal: { onset: 0.5, peak: 1, decay: 5, persist: 0.5 },
    regulation: {
      adaptive: ['ユーモアによる転化', '自己開示的な謝罪（軽い）', '状況の再構成'],
      reappraisal: ['「誰にでもある」という普遍化', '失敗の可愛らしさへの気づき'],
      contraindicated: ['過剰な謝罪と自己批判', '事件の反復的想起', '恥への昇格的解釈'],
    },
    references: ['Keltner (2009)'],
  },
  {
    id: 'contempt',
    name: '軽蔑',
    nameEn: 'Contempt',
    category: 'social',
    coreTheme: '他者を自分より下位の存在と評価する',
    triggers: [
      '他者の能力・道徳性への著しく低い評価',
      '繰り返しの失望や裏切り',
      '自己の価値観と大きくかけ離れた行動の目撃',
      '集団間の競争・差別・偏見',
    ],
    process: [
      '階層的な見下し（怒りの対等な抗議とは異なる）',
      '片側の口角だけが上がる（文化普遍的な表情）',
      '相手に変化を求めない（怒りとの違い）',
      '対象から心理的・物理的に距離をとる',
    ],
    bodyReactions: [
      '片側口角挙上、目のそらし',
      '鼻腔のわずかな広がり',
      '身体の後退や斜めの向き',
    ],
    function: '社会的階層の維持と規範の強化。ゴットマン研究では離婚を予測する最強の単一因子。集団レベルでは非人間化・差別の心理的下地となる。',
    transitions: [
      { to: 'disgust', label: '嫌悪との混合', type: 'BLEND' },
      { to: 'anger', label: '積極的な攻撃へ', type: 'INTENS' },
    ],
    valence: -1, arousal: 0, dominance: 2,
    appraisal: { nov: 0, pleas: -1, goal: 0, cope: 2, norm: -2 },
    temporal: { onset: 60, peak: 60, decay: 1440, persist: 8760 },
    regulation: {
      adaptive: ['怒りへの転換（相手への直接的フィードバック）', '個人と行為の分離'],
      reappraisal: ['他者への敬意と共通の人間性の認識', '軽蔑の関係破壊コストの認識'],
      contraindicated: ['軽蔑の慢性化と定着', '非人間化的言語・思考の維持'],
    },
    references: ['Ekman & Friesen (1986)', 'Gottman (1999)', 'Haslam (2006)'],
  },
  {
    id: 'compassion',
    name: 'コンパッション',
    nameEn: 'Compassion / Pity',
    category: 'social',
    coreTheme: '他者の苦痛を認識し和らげようとする動機',
    triggers: [
      '苦しんでいる他者の目撃',
      '弱者・傷ついた存在への接触',
      '自分自身の失敗・苦しみ（セルフ・コンパッション）',
    ],
    process: [
      '哀れみ（上から目線）とは異なり、対等な立場として苦痛に応答',
      '腹側線条体・腹内側前頭前野・オキシトシン系の関与',
      '共感疲労を起こさず持続的な向社会行動を維持',
      'セルフ・コンパッション：自己への優しさ＋共通の人間性＋マインドフルネス（ネフ）',
    ],
    bodyReactions: [
      '胸の開き、温かみ',
      '迷走神経の活性化（HRV上昇）',
      '近づく行動傾向（恐怖・嫌悪の回避と対照的）',
    ],
    function: '持続的な他者援助と自己回復の基盤。哀れみと異なり、被援助者の自尊心を損なわない。臨床家・介護者の燃え尽き予防の鍵。',
    transitions: [
      { to: 'empathy', label: '共感との連続', type: 'BLEND' },
      { to: 'love', label: '深い思いやりからの絆', type: 'INTENS' },
      { to: 'elevation', label: '感動と重なる', type: 'BLEND' },
      { to: 'sadness', label: '無力感を感じる場合', type: 'APPR' },
    ],
    valence: 1, arousal: 0, dominance: 1,
    appraisal: { nov: 0, pleas: 1, goal: 1, cope: 1, norm: 2 },
    temporal: { onset: 10, peak: 10, decay: 120, persist: 4 },
    regulation: {
      adaptive: ['セルフ・コンパッションの実践', '適切な境界設定', 'コンパッション瞑想（LKM）'],
      reappraisal: ['共感疲労とコンパッション疲労の区別', '苦痛への応答能力を資源として認識'],
      contraindicated: ['他者の代わりに問題を解決しようとする過剰関与', '境界のない自己犠牲'],
    },
    references: ['Neff (2003)', 'Singer & Klimecki (2014)'],
  },
];

export const categoryColors: Record<EmotionCategory, string> = {
  basic: '#E05252',
  positive: '#4A90D9',
  negative: '#8B5CF6',
  social: '#10B981',
};

export const categoryLabels: Record<EmotionCategory, string> = {
  basic: '基本感情',
  positive: 'ポジティブ感情',
  negative: 'ネガティブ感情',
  social: '社会的感情',
};

export const transitionTypeColors: Record<TransitionType, string> = {
  ACUTE:   '#F97316', // オレンジ: 急性
  APPR:    '#A78BFA', // 紫: 再評価
  INTENS:  '#EF4444', // 赤: 強度増大
  CHRONIC: '#6B7280', // グレー: 慢性化
  RESOLV:  '#34D399', // 緑: 解消
  BLEND:   '#60A5FA', // 青: 混合
};

export const transitionTypeLabels: Record<TransitionType, string> = {
  ACUTE:   '急性遷移',
  APPR:    '再評価遷移',
  INTENS:  '強度増大',
  CHRONIC: '慢性化',
  RESOLV:  '解消',
  BLEND:   '感情混合',
};

export function getEmotionById(id: string): Emotion | undefined {
  return emotions.find((e) => e.id === id);
}
